#ddev-generated
version: '3.6'
services:
  mercure:
    container_name: ddev-${DDEV_SITENAME}-mercure
    image: dunglas/mercure:v0.13.0
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
      - './caddy:/etc/caddy'

    environment:
      - SERVER_NAME=${DDEV_HOSTNAME}:81
      - HTTP_EXPOSE=8081:81
      - HTTPS_EXPOSE=8082:81
      - VIRTUAL_HOST=$DDEV_HOSTNAME

    expose:
      - '81'

  web:
    links:
      - "mercure:mercure"