#ddev-generated
version: '3.6'
services:
  mercure:
    container_name: ddev-${DDEV_SITENAME}-mercure
    image: dunglas/mercure:v0.13.0
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
      - './caddy:/etc/caddy'
      - ".:/mnt/ddev_config"

    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8081:8081
      - HTTPS_EXPOSE=8082:8081
      - SERVER_NAME=${DDEV_HOSTNAME}
      - MERCURE_PUBLISHER_JWT_KEY=ChangeMe
      - MERCURE_SUBSCRIBER_JWT_KEY=ChangeMe

    expose:
      - '80'

  web:
    links:
      - "mercure:mercure"