#ddev-generated
version: '3.6'
services:
  mercure:
    container_name: ddev-${DDEV_SITENAME}-mercure
    image: dunglas/mercure:v0.13.0
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
      - './caddy:/etc/caddy'
      - ".:/mnt/ddev_config"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8081:80
      - HTTPS_EXPOSE=8082:80
      - SERVER_NAME=${DDEV_HOSTNAME}:80
      - MERCURE_PUBLISHER_JWT_KEY=ChangeMe
      - MERCURE_SUBSCRIBER_JWT_KEY=ChangeMe

    expose:
      - '80'

  web:
    links:
      - "mercure:mercure"
